from docx import Document as DocxDocument
from docx.shared import Pt, Inches, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY
import os


class DocumentGenerator:
    def __init__(self, output_dir: str = "./output"):
        self.output_dir = output_dir
        if not os.path.exists(output_dir):
            os.makedirs(output_dir)

    def generate_docx(self, filename: str, content: str, title: str = "Legal Document") -> str:
        doc = DocxDocument()

        # Page margins
        for section in doc.sections:
            section.top_margin = Inches(1)
            section.bottom_margin = Inches(1)
            section.left_margin = Inches(1.25)
            section.right_margin = Inches(1.25)

        # Header — Title
        heading = doc.add_heading("", level=0)
        heading.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = heading.add_run(title.upper())
        run.font.name = "Times New Roman"
        run.font.size = Pt(16)
        run.font.bold = True
        run.font.color.rgb = RGBColor(0x1A, 0x1A, 0x2E)

        doc.add_paragraph()  # Spacer

        # Divider paragraph
        div = doc.add_paragraph("_" * 80)
        div.alignment = WD_ALIGN_PARAGRAPH.CENTER

        doc.add_paragraph()

        # Body content — split on newlines
        for line in content.split("\n"):
            para = doc.add_paragraph()
            para.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
            run = para.add_run(line)
            run.font.name = "Times New Roman"
            run.font.size = Pt(12)

        # Footer note
        doc.add_paragraph()
        footer_para = doc.add_paragraph("Generated by Nyastra AI | For Advocate Use Only")
        footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        for run in footer_para.runs:
            run.font.size = Pt(9)
            run.font.italic = True
            run.font.color.rgb = RGBColor(0x88, 0x88, 0x88)

        path = os.path.join(self.output_dir, f"{filename}.docx")
        doc.save(path)
        return path

    def generate_pdf(self, filename: str, content: str, title: str = "Legal Document") -> str:
        path = os.path.join(self.output_dir, f"{filename}.pdf")

        doc = SimpleDocTemplate(
            path,
            pagesize=A4,
            rightMargin=1.25 * inch,
            leftMargin=1.25 * inch,
            topMargin=1 * inch,
            bottomMargin=1 * inch,
        )

        styles = getSampleStyleSheet()

        title_style = ParagraphStyle(
            "NyastraTitle",
            parent=styles["Title"],
            fontName="Times-Bold",
            fontSize=16,
            textColor=colors.HexColor("#1A1A2E"),
            alignment=TA_CENTER,
            spaceAfter=6,
        )

        body_style = ParagraphStyle(
            "NyastraBody",
            parent=styles["Normal"],
            fontName="Times-Roman",
            fontSize=12,
            leading=18,
            alignment=TA_JUSTIFY,
            spaceAfter=6,
        )

        footer_style = ParagraphStyle(
            "NyastraFooter",
            parent=styles["Normal"],
            fontName="Times-Italic",
            fontSize=9,
            textColor=colors.HexColor("#888888"),
            alignment=TA_CENTER,
        )

        story = []

        # Title
        story.append(Paragraph(title.upper(), title_style))
        story.append(Spacer(1, 0.1 * inch))
        story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#C0392B")))
        story.append(Spacer(1, 0.2 * inch))

        # Body — handle newlines, escape XML special chars
        for line in content.split("\n"):
            safe_line = (
                line.replace("&", "&amp;")
                    .replace("<", "&lt;")
                    .replace(">", "&gt;")
            )
            if safe_line.strip():
                story.append(Paragraph(safe_line, body_style))
            else:
                story.append(Spacer(1, 0.1 * inch))

        # Footer
        story.append(Spacer(1, 0.3 * inch))
        story.append(HRFlowable(width="100%", thickness=0.5, color=colors.grey))
        story.append(Spacer(1, 0.1 * inch))
        story.append(Paragraph("Generated by Nyastra AI | For Advocate Use Only", footer_style))

        doc.build(story)
        return path
